image: public.ecr.aws/docker/library/python:3.8

stages:
  - test

run_tests:
  stage: test
  resource_group: ssh-helper-tests
  script:
    - export AWS_REGION=eu-west-1
    - export AWS_DEFAULT_REGION=eu-west-1
    # Install the package
    - pip freeze --all | tee pip_freeze_before.txt
    - pip install '.'
    - pip check
    - pip freeze --all | tee pip_freeze_after.txt
    - pip install '.[cdk,test]'
    - pip check
    - pip freeze --all | tee pip_freeze_after_test.txt
    - '( diff pip_freeze_before.txt pip_freeze_after.txt || : ) | tee pip_freeze_diff.txt'
    - '( diff pip_freeze_after.txt pip_freeze_after_test.txt || : ) | tee pip_freeze_diff_test.txt'
    # Scanning sources
    - bandit -r ./sagemaker_ssh_helper/ ./tests/ *.py --skip B603,B404,B101 2>&1 | tee bandit.txt
    - flake8 --extend-ignore E501,F401,F541,E402 ./sagemaker_ssh_helper/ ./tests/ *.py | tee flake8.txt
    # Update IAM/SSM policies
    - curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
    - apt-get install -y nodejs
    - npm install -g aws-cdk
    - cdk --version
    - REGION=$AWS_REGION
    - USER_ROLE=$GITLAB_ROLE_ARN
    - APP="python -m sagemaker_ssh_helper.cdk.app"
    # cdk bootstrap aws://"$ACCOUNT_ID"/"$REGION" --require-approval never
    - AWS_REGION=$REGION cdk -a "$APP" deploy SSH-IAM-SSM-Stack-Tests 
        --require-approval never -c sagemaker_role=$SAGEMAKER_ROLE -c user_role=$USER_ROLE
    - AWS_REGION=$REGION cdk -a "$APP" deploy SSH-IAM-SSM-Stack
        --require-approval never -c sagemaker_role=$SAGEMAKER_ROLE -c user_role=$USER_ROLE
    - AWS_REGION=$REGION cdk -a "$APP" deploy SSM-Advanced-Tier-Stack
        --require-approval never -c sagemaker_role=$SAGEMAKER_ROLE -c user_role=$USER_ROLE
    - REGION=eu-west-2
    # cdk bootstrap aws://"$ACCOUNT_ID"/"$REGION" --require-approval never
    - AWS_REGION=$REGION cdk -a "$APP" deploy SSM-Advanced-Tier-Stack
        --require-approval never -c sagemaker_role=$SAGEMAKER_ROLE -c user_role=$USER_ROLE
    # Configure local env
    - sm-local-configure
    - source tests/generate_sagemaker_config.sh
    # Assume CI/CD role
    - sts=( $(
        aws sts assume-role
        --role-arn "$GITLAB_ROLE_ARN"
        --role-session-name "gitlab-ci"
        --duration-seconds 18000
        --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
        --output text
        ) )
    - export AWS_ACCESS_KEY_ID=${sts[0]}
    - export AWS_SECRET_ACCESS_KEY=${sts[1]}
    - export AWS_SESSION_TOKEN=${sts[2]}
    # Build BYOC docker image for tests
    - sm-docker build . --file tests/byoc/Dockerfile --repo byoc-ssh:latest
    # Run tests
    - echo "Extra args for pytest - $PYTEST_EXTRA_ARGS"
    - cd tests
    - coverage run -m pytest --html=pytest_report.html --self-contained-html --junitxml=pytest_report.xml -m 'not manual' -o sagemaker_role=$SAGEMAKER_ROLE -o kernel_gateway_name=$KERNEL_GATEWAY_NAME $PYTEST_EXTRA_ARGS
    - coverage report
    - coverage xml
    - cd -
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      junit: tests/pytest_report.xml
      coverage_report:
        coverage_format: cobertura
        path: tests/coverage.xml
    paths:
      - pip_freeze_before.txt
      - pip_freeze_after.txt
      - pip_freeze_diff.txt
      - pip_freeze_after_test.txt
      - pip_freeze_diff_test.txt
      - tests/pytest_report.xml
      - tests/pytest_report.html
      - tests/coverage.xml
      - bandit.txt
      - flake8.txt